/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ervuqkssuserkccrcdir"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVydnVxa3NzdXNlcmtjY3JjZGlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAwODIzNTcsImV4cCI6MjA4NTY1ODM1N30.PZTgOivGzZ1zSAzwrzYd7XSYBUtJo--e_LLP76n1H5k"