// Generate 100 dummy values for each landing page filter

export const authorNameOptions = [
  'John Smith', 'Sarah Johnson', 'Michael Brown', 'Emily Davis', 'David Wilson',
  'Jessica Martinez', 'Christopher Anderson', 'Ashley Taylor', 'Matthew Thomas', 'Amanda Jackson',
  'Daniel White', 'Jennifer Harris', 'James Martin', 'Lisa Thompson', 'Robert Garcia',
  'Mary Rodriguez', 'William Lee', 'Patricia Walker', 'Richard Hall', 'Linda Allen',
  'Joseph Young', 'Barbara King', 'Thomas Wright', 'Susan Lopez', 'Charles Hill',
  'Karen Scott', 'Christopher Green', 'Nancy Adams', 'Steven Baker', 'Betty Nelson',
  'Paul Carter', 'Margaret Mitchell', 'Mark Perez', 'Sandra Roberts', 'Donald Turner',
  'Dorothy Phillips', 'George Campbell', 'Ashley Parker', 'Kenneth Evans', 'Kimberly Edwards',
  'Brian Collins', 'Emily Stewart', 'Ronald Morris', 'Donna Rogers', 'Anthony Reed',
  'Michelle Cook', 'Kevin Morgan', 'Carol Bell', 'Jason Murphy', 'Sarah Bailey',
  'Jeff Rivera', 'Sharon Cooper', 'Ryan Richardson', 'Laura Cox', 'Jacob Howard',
  'Amy Ward', 'Gary Torres', 'Deborah Peterson', 'Nicholas Gray', 'Rebecca Ramirez',
  'Eric James', 'Stephanie Watson', 'Stephen Brooks', 'Catherine Kelly', 'Jonathan Sanders',
  'Virginia Price', 'Larry Bennett', 'Pamela Wood', 'Justin Barnes', 'Brenda Ross',
  'Scott Henderson', 'Nicole Coleman', 'Brandon Jenkins', 'Samantha Perry', 'Benjamin Powell',
  'Christina Long', 'Samuel Patterson', 'Katherine Hughes', 'Raymond Flores', 'Rachel Washington',
  'Gregory Butler', 'Janet Simmons', 'Alexander Foster', 'Carolyn Gonzales', 'Patrick Bryant',
  'Heather Alexander', 'Frank Russell', 'Diane Griffin', 'Douglas Hayes', 'Julie Myers',
  'Dennis Ford', 'Joyce Hamilton', 'Jerry Graham', 'Evelyn Sullivan', 'Tyler Wallace',
  'Frances Woods', 'Aaron Cole', 'Marie West', 'Henry Jordan', 'Theresa Owens'
];

export const campaignOptions = [
  'Q1 2024 Product Launch', 'Q2 2024 Lead Generation', 'Q3 2024 Brand Awareness', 'Q4 2024 Holiday Campaign', 'Summer Sale 2024',
  'Black Friday Special', 'Cyber Monday Deals', 'New Year Promotion', 'Spring Festival', 'Winter Clearance',
  'Back to School Campaign', 'Valentine\'s Day Special', 'Easter Promotion', 'Mother\'s Day Campaign', 'Father\'s Day Special',
  'Independence Day Sale', 'Labor Day Event', 'Halloween Campaign', 'Thanksgiving Special', 'Christmas Promotion',
  'Webinar Series 2024', 'Free Trial Campaign', 'Demo Request Drive', 'Newsletter Signup Push', 'Ebook Download Campaign',
  'Whitepaper Distribution', 'Case Study Showcase', 'Product Demo Series', 'Customer Success Stories', 'Partner Program Launch',
  'Referral Program 2024', 'Loyalty Rewards Campaign', 'Beta Testing Initiative', 'Early Access Program', 'VIP Customer Event',
  'Industry Conference 2024', 'Trade Show Promotion', 'Virtual Event Series', 'Workshop Registration', 'Training Program Launch',
  'Certification Course', 'Annual Summit 2024', 'Regional Meetup', 'User Conference', 'Developer Workshop',
  'Mobile App Launch', 'Feature Release Campaign', 'Platform Update Announcement', 'Integration Partnership', 'API Launch',
  'Enterprise Solution Campaign', 'SMB Focus Initiative', 'Startup Program', 'Education Sector Drive', 'Healthcare Campaign',
  'Retail Industry Focus', 'Finance Sector Campaign', 'Technology Innovation', 'Digital Transformation', 'Cloud Infrastructure',
  'Security Awareness', 'Compliance Initiative', 'Sustainability Campaign', 'Diversity & Inclusion', 'Corporate Social Responsibility',
  'Customer Appreciation', 'Anniversary Celebration', 'Milestone Achievement', 'Award Announcement', 'Press Release Campaign',
  'Media Partnership', 'Influencer Collaboration', 'Social Media Blitz', 'Content Marketing Push', 'SEO Campaign 2024',
  'PPC Advertising Drive', 'Email Marketing Series', 'SMS Campaign', 'Direct Mail Integration', 'Retargeting Initiative',
  'Conversion Optimization', 'Landing Page Testing', 'A/B Test Campaign', 'Personalization Project', 'Customer Journey Mapping',
  'Lead Nurturing Program', 'Sales Enablement', 'Account-Based Marketing', 'Demand Generation', 'Growth Marketing Initiative',
  'Customer Retention Focus', 'Churn Reduction Campaign', 'Upsell Opportunity Drive', 'Cross-sell Initiative', 'Win-back Campaign',
  'Reactivation Series', 'Onboarding Improvement', 'Product Education', 'Feature Adoption Push', 'Usage Analytics Campaign'
];

export const domainOptions = [
  'landing.company.com', 'campaigns.company.com', 'promo.company.com', 'events.company.com', 'offers.company.com',
  'webinars.company.com', 'demo.company.com', 'trial.company.com', 'signup.company.com', 'register.company.com',
  'info.company.com', 'learn.company.com', 'resources.company.com', 'downloads.company.com', 'academy.company.com',
  'training.company.com', 'education.company.com', 'workshop.company.com', 'summit.company.com', 'conference.company.com',
  'go.company.com', 'try.company.com', 'get.company.com', 'start.company.com', 'join.company.com',
  'marketing.company.com', 'sales.company.com', 'partners.company.com', 'developers.company.com', 'enterprise.company.com',
  'business.company.com', 'solutions.company.com', 'products.company.com', 'services.company.com', 'platform.company.com',
  'cloud.company.com', 'app.company.com', 'mobile.company.com', 'web.company.com', 'digital.company.com',
  'tech.company.com', 'innovation.company.com', 'lab.company.com', 'research.company.com', 'insights.company.com',
  'analytics.company.com', 'data.company.com', 'intelligence.company.com', 'metrics.company.com', 'reports.company.com',
  'dashboard.company.com', 'portal.company.com', 'hub.company.com', 'center.company.com', 'support.company.com',
  'help.company.com', 'docs.company.com', 'api.company.com', 'status.company.com', 'community.company.com',
  'forum.company.com', 'discussion.company.com', 'feedback.company.com', 'ideas.company.com', 'roadmap.company.com',
  'changelog.company.com', 'releases.company.com', 'updates.company.com', 'news.company.com', 'press.company.com',
  'media.company.com', 'stories.company.com', 'success.company.com', 'testimonials.company.com', 'reviews.company.com',
  'customers.company.com', 'clients.company.com', 'users.company.com', 'members.company.com', 'subscribers.company.com',
  'vip.company.com', 'premium.company.com', 'pro.company.com', 'plus.company.com', 'elite.company.com',
  'exclusive.company.com', 'early-access.company.com', 'beta.company.com', 'preview.company.com', 'coming-soon.company.com',
  'launch.company.com', 'new.company.com', 'fresh.company.com', 'next.company.com', 'future.company.com',
  'special.company.com', 'limited.company.com', 'flash.company.com', 'hot.company.com', 'trending.company.com'
];

export const htmlTitleOptions = [
  'Get Started with Our Free Trial Today', 'Download Your Free Ebook Now', 'Register for Our Exclusive Webinar', 'Request a Personalized Demo', 'Sign Up for Early Access',
  'Join Our Growing Community', 'Learn More About Our Solutions', 'Discover the Power of Automation', 'Transform Your Business Today', 'Unlock Your Full Potential',
  'Experience Innovation First-hand', 'Start Your Journey with Us', 'Elevate Your Marketing Strategy', 'Boost Your Sales Performance', 'Maximize Your ROI',
  'Streamline Your Workflow', 'Optimize Your Operations', 'Accelerate Your Growth', 'Scale Your Business Efficiently', 'Drive Better Results',
  'Increase Customer Engagement', 'Improve Conversion Rates', 'Enhance User Experience', 'Build Stronger Relationships', 'Create Lasting Impact',
  'Master the Art of Digital Marketing', 'The Ultimate Guide to Success', 'Everything You Need to Know', 'Expert Tips and Tricks', 'Best Practices Revealed',
  'Industry-Leading Solutions', 'Award-Winning Platform', 'Trusted by Thousands', 'Proven Results Guaranteed', 'Risk-Free Trial Available',
  'No Credit Card Required', 'Cancel Anytime - No Strings Attached', 'Money-Back Guarantee', 'Limited Time Offer', 'Exclusive Deal Inside',
  'Save Big on Premium Features', 'Upgrade Your Plan Today', 'Switch and Save', 'Compare Our Plans', 'Find Your Perfect Plan',
  'Custom Solutions for Your Business', 'Enterprise-Grade Security', 'White-Glove Onboarding', 'Dedicated Support Team', '24/7 Customer Service',
  'Real-Time Analytics Dashboard', 'Advanced Reporting Tools', 'Powerful Integration Options', 'Seamless API Access', 'Mobile-First Design',
  'Responsive Across All Devices', 'Lightning-Fast Performance', 'Unmatched Reliability', 'Industry-Best Uptime', 'Secure and Compliant',
  'GDPR Ready Solution', 'SOC 2 Certified Platform', 'ISO Compliant Infrastructure', 'Bank-Level Encryption', 'Privacy-First Approach',
  'Join 10,000+ Happy Customers', 'See Why Teams Love Us', 'Read Customer Success Stories', 'View Case Studies', 'Check Out Testimonials',
  'Watch Product Demo Videos', 'Browse Our Resource Library', 'Access Free Templates', 'Download Useful Guides', 'Get Expert Insights',
  'Subscribe to Our Newsletter', 'Follow for Latest Updates', 'Connect with Our Community', 'Attend Our Next Event', 'Reserve Your Spot Now',
  'Early Bird Pricing Available', 'Group Discount Offered', 'Partner Program Benefits', 'Referral Rewards Waiting', 'Affiliate Opportunities',
  'Become a Certified Partner', 'Join Our Reseller Network', 'Agency Solutions Available', 'White Label Options', 'OEM Partnerships',
  'Educational Pricing', 'Nonprofit Discounts', 'Startup Package Available', 'Student Discount Program', 'Government Pricing',
  'Healthcare Solutions', 'Financial Services Platform', 'Retail Technology', 'Manufacturing Tools', 'Professional Services Software'
];

export const languageOptions = [
  'English (US)', 'English (UK)', 'English (Canada)', 'English (Australia)', 'Spanish (Spain)',
  'Spanish (Mexico)', 'Spanish (Argentina)', 'French (France)', 'French (Canada)', 'German',
  'Italian', 'Portuguese (Brazil)', 'Portuguese (Portugal)', 'Dutch', 'Swedish',
  'Norwegian', 'Danish', 'Finnish', 'Polish', 'Russian',
  'Ukrainian', 'Czech', 'Hungarian', 'Romanian', 'Bulgarian',
  'Greek', 'Turkish', 'Arabic', 'Hebrew', 'Hindi',
  'Chinese (Simplified)', 'Chinese (Traditional)', 'Japanese', 'Korean', 'Thai',
  'Vietnamese', 'Indonesian', 'Malay', 'Filipino', 'Bengali',
  'Urdu', 'Persian', 'Swahili', 'Amharic', 'Zulu',
  'Afrikaans', 'Icelandic', 'Welsh', 'Irish', 'Scottish Gaelic',
  'Catalan', 'Basque', 'Galician', 'Slovenian', 'Croatian',
  'Serbian', 'Bosnian', 'Macedonian', 'Albanian', 'Latvian',
  'Lithuanian', 'Estonian', 'Georgian', 'Armenian', 'Azerbaijani',
  'Kazakh', 'Uzbek', 'Mongolian', 'Nepali', 'Sinhala',
  'Burmese', 'Khmer', 'Lao', 'Tibetan', 'Pashto',
  'Kurdish', 'Punjabi', 'Tamil', 'Telugu', 'Malayalam',
  'Kannada', 'Marathi', 'Gujarati', 'Oriya', 'Assamese',
  'Esperanto', 'Latin', 'Sanskrit', 'Hawaiian', 'Maori',
  'Samoan', 'Tongan', 'Fijian', 'Tahitian', 'Luxembourgish',
  'Maltese', 'Faroese', 'Greenlandic', 'Inuktitut', 'Cree'
];

export const nameOptions = [
  'Homepage Hero Section', 'Product Launch Landing Page', 'Free Trial Signup Form', 'Webinar Registration Page', 'Ebook Download Portal',
  'Demo Request Form', 'Contact Sales Page', 'Pricing Comparison Table', 'Feature Showcase', 'Customer Success Stories',
  'Case Study Download', 'Whitepaper Access', 'Newsletter Subscription', 'Event Registration Form', 'Workshop Signup',
  'Training Program Enrollment', 'Certification Course Landing', 'Partner Program Application', 'Affiliate Signup Form', 'Reseller Portal',
  'Beta Testing Application', 'Early Access Request', 'VIP Program Enrollment', 'Premium Plan Upgrade', 'Enterprise Contact Form',
  'SMB Solutions Page', 'Startup Program Landing', 'Education Sector Offering', 'Healthcare Solutions', 'Finance Industry Page',
  'Retail Technology Landing', 'Manufacturing Solutions', 'Professional Services', 'Consulting Services Page', 'Support Services',
  'Implementation Services', 'Integration Services', 'Custom Development', 'API Documentation',
  'Developer Portal Landing', 'Technical Documentation', 'User Guide Access', 'Video Tutorial Library', 'Knowledge Base Portal',
  'FAQ Landing Page', 'Support Center', 'Help Desk Portal', 'Community Forum Landing', 'Discussion Board',
  'Customer Portal Login', 'Partner Portal Access', 'Admin Dashboard Landing', 'Analytics Dashboard', 'Reporting Portal',
  'Mobile App Download', 'Desktop App Download', 'Browser Extension', 'Plugin Installation', 'Add-on Marketplace',
  'Theme Gallery', 'Template Library', 'Resource Center', 'Blog Subscription', 'Podcast Landing',
  'Video Series Page', 'Infographic Library', 'Slide Deck Downloads', 'Tool Kit Access', 'Checklist Downloads',
  'Annual Report Access', 'Quarterly Results', 'Investor Relations', 'Press Release Archive', 'Media Kit Download',
  'Brand Guidelines', 'Logo Assets', 'Marketing Materials', 'Sales Collateral', 'Partner Resources',
  'About Us Landing', 'Company History', 'Leadership Team', 'Careers Portal', 'Job Listings',
  'Company Culture Page', 'Benefits Overview', 'Diversity Initiative', 'Sustainability Commitment', 'Corporate Responsibility',
  'Security Overview', 'Compliance Center', 'Privacy Policy Landing', 'Terms of Service', 'Cookie Policy',
  'GDPR Compliance', 'Accessibility Statement', 'Service Status', 'Maintenance Schedule', 'System Requirements'
];

export const slugOptions = [
  '/free-trial', '/get-started', '/demo-request', '/sign-up', '/register',
  '/pricing', '/plans', '/compare-plans', '/features', '/solutions',
  '/enterprise', '/small-business', '/startups', '/education', '/nonprofit',
  '/healthcare', '/finance', '/retail', '/manufacturing', '/technology',
  '/webinar', '/event', '/conference', '/workshop', '/training',
  '/certification', '/course', '/academy', '/learn', '/resources',
  '/ebook', '/whitepaper', '/case-study', '/guide', '/template',
  '/toolkit', '/checklist', '/infographic', '/video', '/podcast',
  '/blog', '/newsletter', '/subscribe', '/contact', '/sales',
  '/support', '/help', '/faq', '/documentation', '/api-docs',
  '/developers', '/partners', '/affiliates', '/resellers', '/agencies',
  '/community', '/forum', '/discussion', '/feedback', '/ideas',
  '/about', '/company', '/team', '/careers', '/jobs',
  '/culture', '/values', '/mission', '/vision', '/history',
  '/news', '/press', '/media', '/investors', '/reports',
  '/security', '/privacy', '/terms', '/compliance', '/gdpr',
  '/status', '/maintenance', '/updates', '/changelog', '/releases',
  '/download', '/mobile-app', '/desktop-app', '/extension', '/plugin',
  '/themes', '/templates', '/marketplace', '/integrations', '/addons',
  '/success-stories', '/testimonials', '/reviews', '/customers', '/portfolio'
];

export const stateOptions = [
  'Published', 'Draft', 'Scheduled', 'Archived', 'Under Review',
  'Pending Approval', 'In Progress', 'Ready to Publish', 'Needs Revision', 'On Hold',
  'Cancelled', 'Expired', 'Active', 'Inactive', 'Suspended',
  'Paused', 'Live', 'Offline', 'Testing', 'Staging',
  'Production', 'Development', 'Beta', 'Alpha', 'Preview',
  'Coming Soon', 'Maintenance', 'Deprecated', 'Legacy', 'Retired',
  'Migrating', 'Updating', 'Syncing', 'Processing', 'Queued',
  'Failed', 'Error', 'Warning', 'Success', 'Completed',
  'Partial', 'Limited', 'Full', 'Enhanced', 'Standard',
  'Basic', 'Premium', 'Enterprise', 'Professional', 'Personal',
  'Trial', 'Freemium', 'Paid', 'Subscription', 'One-time',
  'Monthly', 'Annual', 'Quarterly', 'Custom', 'Flexible',
  'Fixed', 'Variable', 'Dynamic', 'Static', 'Responsive',
  'Adaptive', 'Mobile', 'Desktop', 'Tablet', 'Universal',
  'Regional', 'Global', 'Local', 'International', 'Domestic',
  'Public', 'Private', 'Internal', 'External', 'Restricted',
  'Open', 'Closed', 'Locked', 'Unlocked', 'Protected',
  'Secure', 'Verified', 'Unverified', 'Validated', 'Pending Validation',
  'Approved', 'Rejected', 'Flagged', 'Reported', 'Resolved'
];
